<?php
/**
 * Hand-drawn marks shared with the splash mockup: the platform icons and the placeholder avatar.
 * Generated by brand/src/build_theme.py. Do not edit here.
 *
 * @package generation-maine
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Inner SVG for a platform mark, 24 units, one color (currentColor).
 *
 * @return array<string,string>
 */
function gm_mark_paths() {
	return array(
		"instagram" => "<rect x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"/><circle cx=\"12\" cy=\"12\" r=\"4.2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"/><circle cx=\"17.3\" cy=\"6.7\" r=\"1.3\" fill=\"currentColor\"/>",
		"tiktok" => "<path d=\"M13.2 2h3.1c.2 2.4 1.7 4 4.2 4.3v3.1c-1.6 0-3-.5-4.2-1.3v6.6a6 6 0 1 1-6-6c.4 0 .7 0 1 .1v3.2a2.9 2.9 0 1 0 1.9 2.7V2z\" fill=\"currentColor\"/>",
		"youtube" => "<path d=\"M21.6 7.2a2.5 2.5 0 0 0-1.8-1.8C18.2 5 12 5 12 5s-6.2 0-7.8.4A2.5 2.5 0 0 0 2.4 7.2C2 8.8 2 12 2 12s0 3.2.4 4.8a2.5 2.5 0 0 0 1.8 1.8C5.8 19 12 19 12 19s6.2 0 7.8-.4a2.5 2.5 0 0 0 1.8-1.8c.4-1.6.4-4.8.4-4.8s0-3.2-.4-4.8z\" fill=\"currentColor\"/><path d=\"M10 9v6l5-3z\" fill=\"var(--icon-bg,#fff)\"/>",
		"substack" => "<rect x=\"4\" y=\"3\" width=\"16\" height=\"2.4\" fill=\"currentColor\"/><rect x=\"4\" y=\"8\" width=\"16\" height=\"2.4\" fill=\"currentColor\"/><path d=\"M4 13h16v8l-8-4.4L4 21z\" fill=\"currentColor\"/>"
	);
}

/**
 * A platform mark as an inline SVG.
 *
 * @param string $name instagram, tiktok, youtube or substack.
 * @param string $class CSS class on the svg.
 * @return string
 */
function gm_mark( $name, $class = 'ic' ) {
	$paths = gm_mark_paths();
	if ( ! isset( $paths[ $name ] ) ) {
		return '';
	}
	return '<svg class="' . esc_attr( $class ) . '" viewBox="0 0 24 24" aria-hidden="true">' . $paths[ $name ] . '</svg>';
}

/**
 * The placeholder avatar, a circle with a simple figure. Replaced by the creator's photo when one is set.
 *
 * @return string
 */
function gm_avatar_placeholder() {
	return "<svg class=\"av\" viewBox=\"0 0 40 40\" aria-hidden=\"true\"><circle cx=\"20\" cy=\"20\" r=\"20\" fill=\"rgba(255,255,255,.22)\"/><circle cx=\"20\" cy=\"15.5\" r=\"6.5\" fill=\"#FFFFFF\"/><path d=\"M8.5 34a11.5 11.5 0 0 1 23 0\" fill=\"#FFFFFF\"/></svg>";
}

/**
 * A logo file from assets/img as inline SVG, with a class and no role attribute.
 *
 * @param string $name File name without .svg.
 * @param string $class Class for the svg element.
 * @return string
 */
function gm_logo( $name, $class = 'lk' ) {
	$file = get_theme_file_path( 'assets/img/' . $name . '.svg' );
	if ( ! file_exists( $file ) ) {
		return '';
	}
	$svg = (string) file_get_contents( $file ); // phpcs:ignore WordPressVIPMinimum.Performance.FetchingRemoteData.FileGetContentsUnknown
	$svg = str_replace( 'role="img"', '', $svg );
	return preg_replace( '/<svg /', '<svg class="' . esc_attr( $class ) . '" ', $svg, 1 );
}
